package com.example.dto;
// Generated 14-05-2019 09:58:12 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */

public class ContactoDto implements java.io.Serializable {

	private Long id;
	private String documento;
	private String firstName;
	private String lastName;

	//public ContactoDto() {	}

	public ContactoDto(Long id,String documento, String firstName, String lastName) {
		this.id=id;
		this.documento = documento;
		this.firstName = firstName;
		this.lastName = lastName;
		
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "firstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	

}
