package com.example.dto;
// Generated 14-05-2019 09:58:12 by Hibernate Tools 5.1.10.Final


/**
 * Contacto generated by hbm2java
 */

public class PerfilDto implements _DTOEntity {

	private int id=0;
	private String glosa;
	private boolean activo;
	

	public PerfilDto() {
		super();
		// TODO Auto-generated constructor stub
	}


	public PerfilDto(int id,String glosa,boolean activo) 
	{
		this.id=id;
		this.glosa=glosa;
		this.activo=activo;
	}

	
	public int getId() 
	{
		return this.id;
	}

	public void setId(int id) 
	{
		this.id = id;
	}

	
	public String getGlosa() 
	{
		return this.glosa;
	}

	public void setGlosa(String glosa) 
	{
		this.glosa = glosa;
	}


	public boolean isActivo() {
		return activo;
	}


	public void setActivo(boolean activo) {
		this.activo = activo;
	}


	@Override
	public String toString() {
		return "PerfilDto [id=" + id + ", glosa=" + glosa + ", activo=" + activo + "]";
	}
	
	
}
