package com.example.dto;
// Generated 14-05-2019 09:58:12 by Hibernate Tools 5.1.10.Final


/**
 * Contacto generated by hbm2java
 */

public class TipoDocumentoDto implements _DTOEntity {

	private Long id;
	private String glosa;
	

	//public ContactoDto() {	}

	public TipoDocumentoDto(Long id,String glosa) {
		this.id=id;
		this.glosa = glosa;
		
		
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public String getGlosa() {
		return this.glosa;
	}

	public void setGlosa(String glosa) {
		this.glosa = glosa;
	}
}
