runtime: java
env: flex
service: springboot02

handlers:
  - url: /.*
    script: this field is required, but ignored
    
manual_scaling:
  instances: 1
  
readiness_check:
    app_start_timeout_sec: 1800

resources:
  cpu: 1
  memory_gb: 0.7