runtime: java
env: flex
service: springboot02

handlers:
  - url: /.*
    script: this field is required, but ignored
    
manual_scaling:
  instances: 1
  
readiness_check:
    app_start_timeout_sec: 1800

resources:
  cpu: 1
  memory_gb: 4
  
beta_settings:
      cloud_sql_instances: "my-project-4-19763:us-central1:springboot02"