package com.example.entities;
// Generated 14-05-2019 09:58:12 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.eclipse.persistence.annotations.Customizer;

import com.example.config.ColumnPosition;
import com.example.config.EntityColumnPositionCustomizer;


/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "Persona")
@Customizer(EntityColumnPositionCustomizer.class)
public class Persona extends _BaseEntity {

	/**
	 * 
	 */
		
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@ColumnPosition(position = 0) 
	private Long id;
	
	
	@Column(name = "documento")
	@ColumnPosition(position = 1) 
	private int documento;
	
	@Column(name = "nombres")
	@ColumnPosition(position = 2)
	private String nombres;
	
	@Column(name = "apellidos")
	@ColumnPosition(position = 3)
	private String apellidos;
	
	@Column(name = "sexo")
	@ColumnPosition(position = 4)
	private String sexo;
	
	@Column(name = "email")
	@ColumnPosition(position = 5)
	private String email;
	
	@Column(name = "fechaNacimiento")
	@ColumnPosition(position = 6)
	private Calendar fechaNacimiento;
	

	public Persona() {
	}

	

	public Persona(int documento, String nombres, String apellidos, String sexo, String email,Calendar fechaNacimiento) {
		this.documento = documento;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.email = email;
		this.fechaNacimiento=fechaNacimiento;
	}

	

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	

	//@JsonIgnore
	
	public int getDocumento() {
		return this.documento;
	}

	@Override
	public String toString() {
		return "Persona [id=" + this.getId() + ", documento=" + this.getDocumento() + ", nombres=" + nombres + ", lastName="
				+ apellidos + ", sexo=" + sexo + ", email=" + email + "]";
	}

	public void setDocumento(int documento) {
		this.documento = documento;
	}

	
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public Calendar getFechaNacimiento() {
		return fechaNacimiento;
	}



	public void setFechaNacimiento(Calendar fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}


}
