package com.example.entities;
// Generated 14-05-2019 09:58:12 by Hibernate Tools 5.1.10.Final

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.Customizer;

import com.example.config.ColumnPosition;
import com.example.config.EntityColumnPositionCustomizer;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "segu_perfil")
@Customizer(EntityColumnPositionCustomizer.class)
public class Segu_Perfil extends _BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPerfil", unique = true, nullable = false)
	@ColumnPosition(position = 0) 
	private int idPerfil;
	
	
	

	@Column(name = "glosa", length = 50)
	@ColumnPosition(position = 1) 
	private String glosa;
	
		
	//@OneToOne(fetch = FetchType.LAZY, cascade =  CascadeType.ALL, mappedBy = "perfil")
   	//private Segu_Usuario usuario;
	
   
	public Segu_Perfil() {
	}

	
	public Segu_Perfil(int idPerfil,String glosa) {
		this.idPerfil=idPerfil;
		this.glosa = glosa;
	}
	
	public int getIdPerfil() {
		return idPerfil;
	}



	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}
	

	
	public String getGlosa() {
		return this.glosa;
	}

	public void setGlosa(String glosa) {
		this.glosa = glosa;
	}
	
	   
	/*
	public Segu_Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Segu_Usuario usuario) {
		this.usuario = usuario;
	}*/

	@Override
	public String toString() {
		return "Segu_Perfil [id=" + this.getIdPerfil() + ", glosa=" + glosa + "]";
	}
	
	

	

}
