package com.example.entities;
// Generated 14-05-2019 09:58:12 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "TipoDocumento")
public class TipoDocumento implements java.io.Serializable {

	private Integer id;
	private String glosa;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public TipoDocumento() {
	}

	public TipoDocumento(String glosa, Set<Persona> personas) {
		this.glosa = glosa;
		this.personas = personas;
	}
	/*
	public TipoDocumento(int id,String glosa)
	{
		this.id=id;
		this.glosa=glosa;
	}*/
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "glosa", length = 50)
	public String getGlosa() {
		return this.glosa;
	}

	public void setGlosa(String glosa) {
		this.glosa = glosa;
	}
    
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	@Override
	public String toString() {
		return "TipoDocumento [id=" + id + ", glosa=" + glosa + "]";
	}

}
